listOfGames = {
	"sunshine",
	"HelloWorld",
	"that floppy",
	"bricks bricks everywhere",
	"ddr",
	"torch",
	"the car",
	"don't blink",
	"dodge everything",
	"face match",
	"ice cream truck",
	"i will derive",
	"waste the ink",
	"WaveAtTheTour",
	"jet pack man",
	'gun or umbrella',
	"challenge of the ni",
	"fix the kerning",
	"MatchParens",
	"cannon",
	"catch the toast",
	"RockClimb",
	"pirate",
	"leek spin",
	"challenge of the ni",
	"tp party",
	"do you like waffles",
	"HackTheGibson"
}

return listOfGames
